name: Publish

on:
  push:
    branches:
      - development
      - master

jobs:
  publish:
    name: Simple 'box publish'
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Ortus-Solutions/commandbox-action@v1
        env:
          box_config_endpoints_forgebox_APIToken: ${{ secrets.FORGEBOX_TOKEN }}
        with:
          cmd: publish
